# 内存管理
Swift也是采取基于引用计数的ARC内存管理方案（针对堆空间）,Swift的ARC中有3种引用:
* `强引用（strong reference）`：默认情况下，引用都是强引用
* `弱引用（weak reference）`：通过weak定义弱引用
    * 必须是可选类型的var，因为实例销毁后，ARC会自动将弱引用设置为nil
    * ARC自动给弱引用设置nil时，不会触发属性观察器`willSet/didSet`
* `无主引用（unowned reference）`：通过unowned定义无主引用
    * 不会产生强引用，实例销毁后仍然存储着实例的内存地址（类似于OC中的`unsafe_unretained`）
    * 试图在实例销毁后访问无主引用，会产生运行时错误（野指针）`Fatal error: Attempted to read an unowned reference but object 0x0 was already deallocated`

>`weak`、`unowned`只能用在类实例上面

## 循环引用（Reference Cycle）
`weak`、`unowned` 都能解决循环引用的问题，`unowned` 要比 `weak` 少一些性能消耗
* 在生命周期中可能会变为 nil 的使用 `weak`
* 初始化赋值后再也不会变为 nil 的使用 `unowned`

## 闭包的循环引用
闭包表达式默认会对用到的外层对象产生额外的强引用（对外层对象进行了retain操作）。

下面代码会产生循环引用，导致Person对象无法释放（看不到Person的deinit被调用）
```swift
class Person {
    var fn: ((Int) -> ())?
    func run() { print("run") }
    deinit { print("deinit") }
}
func test() {
    let p = Person()
    p.fn = { (_) in p.run() }
}
test()
```
这是因为调用fn闭包的过程中，对实例对象p进行了强引用，导致循环引用p对象无法释放。在闭包表达式的捕获列表声明`weak`或`unowned`引用，解决循环引用问题
```swift
// [] 内是捕获列表 ()内是参数列表
p.fn = {
    [weak p](v) in
    p?.run()
}

p.fn = {
    [unowned p](v) in
    p.run()
}
```

如果想在定义闭包属性的同时引用self，这个闭包必须是`lazy`的（因为在实例初始化完毕之后才能引用self）
```swift
class Person {
    // fn内部如果用到了实例成员（属性、方法）,编译器会强制要求明确写出self
    lazy var fn: (() -> ()) = {
        [weak self] in
        self?.run()
    }
    func run() { print("run") }
    deinit { print("deinit") }
}
```

**如果lazy属性是闭包调用的结果**，那么不用考虑循环引用的问题（因为闭包调用后，闭包的生命周期就结束了）
```swift
class Person {
    var age: Int = 0
    lazy var getAge: Int = {
        self.age
    }()
    deinit { print("deinit") }
}
```

## 逃逸闭包 @escaping
非逃逸闭包、逃逸闭包，一般都是当做参数传递给函数。
* `非逃逸闭包`：闭包调用发生在函数结束前，闭包调用在函数作用域内
* `逃逸闭包`：闭包有可能在函数结束后调用，闭包调用逃离了函数的作用域，需要通过`@escaping`声明

```swift
import Dispatch
typealias Fn = () -> ()
// fn是非逃逸闭包
func test1(_ fn: Fn) { fn() }
// fn是逃逸闭包
var gFn: Fn?
func test2(_ fn: @escaping Fn) { gFn = fn }
// fn是逃逸闭包
func test3(_ fn: @escaping Fn) {
    DispatchQueue.global().async {
        fn()
    }
}
class Person {
    var fn: Fn
    // fn是逃逸闭包
    init(fn: @escaping Fn) {
        self.fn = fn
    }
    func run() {
        // DispatchQueue.global().async也是一个逃逸闭包
        // 它用到了实例成员（属性、方法），编译器会强制要求明确写出self
        DispatchQueue.global().async {
            self.fn()   
        }
    }
}
```

>逃逸闭包不可以捕获`inout`参数

```swift
typealias Fn = () -> ()

func other1(_ fn: Fn) { fn() }
func other2(_ fn: @escaping Fn) { fn() }

func test(value: inout Int) -> Fn {
    other1 { value += 1 }
    // error: 逃逸闭包不能捕获inout参数
    other2 { value += 1 }
    func plus() { value += 1 }
    // error: 逃逸闭包不能捕获inout参数,plus由于在函数外部调用，也属于逃逸闭包
    return plus
}
```

## 内存访问冲突（Conflicting Access to Memory）
内存访问冲突会在两个访问满足下列条件时发生：
* 至少一个是写入操作
* 它们访问的是同一块内存
* 它们的访问时间重叠（比如在同一个函数内）

```swift
// 不存在内存访问冲突
var number = 1
func plus(_ num: inout Int) -> Int { num + 1 }
number = plus(&number)

// 存在内存访问冲突
error: Execution was interrupted, reason: signal SIGABRT.
// Simultaneous accesses to 0x0, but modification requires exclusive access
var step = 1
func increment(_ num: inout Int) { num += step }
increment(&step)

// 解决内存访问冲突
var copyOfStep = step
increment(&copyOfStep)
step = copyOfStep
```

满足下面的条件时，不会出现内存访问冲突
1. 你只访问实例存储属性，不是计算属性或者类属性
2. 结构体是局部变量而非全局变量
3. 结构体要么没有被闭包捕获要么只被非逃逸闭包捕获